package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePreOrder<M extends BasePreOrder<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
		return (M)this;
	}
	
	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public M setOrderArea(java.lang.String orderArea) {
		set("order_area", orderArea);
		return (M)this;
	}
	
	public java.lang.String getOrderArea() {
		return getStr("order_area");
	}

	public M setOrderProduct(java.lang.Integer orderProduct) {
		set("order_product", orderProduct);
		return (M)this;
	}
	
	public java.lang.Integer getOrderProduct() {
		return getInt("order_product");
	}

	public M setOrderName(java.lang.String orderName) {
		set("order_name", orderName);
		return (M)this;
	}
	
	public java.lang.String getOrderName() {
		return getStr("order_name");
	}

	public M setOrderTel(java.lang.String orderTel) {
		set("order_tel", orderTel);
		return (M)this;
	}
	
	public java.lang.String getOrderTel() {
		return getStr("order_tel");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

}
