package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setProductCode(java.lang.String productCode) {
		set("product_code", productCode);
		return (M)this;
	}
	
	public java.lang.String getProductCode() {
		return getStr("product_code");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setProductIntro(java.lang.String productIntro) {
		set("product_intro", productIntro);
		return (M)this;
	}
	
	public java.lang.String getProductIntro() {
		return getStr("product_intro");
	}

	public M setProductLimit(java.math.BigDecimal productLimit) {
		set("product_limit", productLimit);
		return (M)this;
	}
	
	public java.math.BigDecimal getProductLimit() {
		return get("product_limit");
	}

	public M setProductPeriod(java.lang.String productPeriod) {
		set("product_period", productPeriod);
		return (M)this;
	}
	
	public java.lang.String getProductPeriod() {
		return getStr("product_period");
	}

	public M setProductRateMin(java.math.BigDecimal productRateMin) {
		set("product_rate_min", productRateMin);
		return (M)this;
	}
	
	public java.math.BigDecimal getProductRateMin() {
		return get("product_rate_min");
	}

	public M setInterestWay(java.lang.String interestWay) {
		set("interest_way", interestWay);
		return (M)this;
	}
	
	public java.lang.String getInterestWay() {
		return getStr("interest_way");
	}

	public M setDrawWay(java.lang.String drawWay) {
		set("draw_way", drawWay);
		return (M)this;
	}
	
	public java.lang.String getDrawWay() {
		return getStr("draw_way");
	}

	public M setApplyWay(java.lang.String applyWay) {
		set("apply_way", applyWay);
		return (M)this;
	}
	
	public java.lang.String getApplyWay() {
		return getStr("apply_way");
	}

	public M setExclude(java.lang.String exclude) {
		set("exclude", exclude);
		return (M)this;
	}
	
	public java.lang.String getExclude() {
		return getStr("exclude");
	}

	public M setInstitution(java.lang.String institution) {
		set("institution", institution);
		return (M)this;
	}
	
	public java.lang.String getInstitution() {
		return getStr("institution");
	}

	public M setLogoPath(java.lang.String logoPath) {
		set("logo_path", logoPath);
		return (M)this;
	}
	
	public java.lang.String getLogoPath() {
		return getStr("logo_path");
	}

	public M setProductType(java.lang.Integer productType) {
		set("product_type", productType);
		return (M)this;
	}
	
	public java.lang.Integer getProductType() {
		return getInt("product_type");
	}

	public M setProductStatus(java.lang.Integer productStatus) {
		set("product_status", productStatus);
		return (M)this;
	}
	
	public java.lang.Integer getProductStatus() {
		return getInt("product_status");
	}

	public M setBannerPath(java.lang.String bannerPath) {
		set("banner_path", bannerPath);
		return (M)this;
	}
	
	public java.lang.String getBannerPath() {
		return getStr("banner_path");
	}

	public M setProductRateMax(java.math.BigDecimal productRateMax) {
		set("product_rate_max", productRateMax);
		return (M)this;
	}
	
	public java.math.BigDecimal getProductRateMax() {
		return get("product_rate_max");
	}

	public M setPassRate(java.math.BigDecimal passRate) {
		set("pass_rate", passRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getPassRate() {
		return get("pass_rate");
	}

	public M setServiceEarn(java.math.BigDecimal serviceEarn) {
		set("service_earn", serviceEarn);
		return (M)this;
	}
	
	public java.math.BigDecimal getServiceEarn() {
		return get("service_earn");
	}

}
