package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatisticsRecord<M extends BaseStatisticsRecord<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}
	
	public java.lang.String getUserAccount() {
		return getStr("user_account");
	}

	public M setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
		return (M)this;
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}

	public M setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
		return (M)this;
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public M setRecommendCount(java.lang.Integer recommendCount) {
		set("recommend_count", recommendCount);
		return (M)this;
	}
	
	public java.lang.Integer getRecommendCount() {
		return getInt("recommend_count");
	}

	public M setApplyCount(java.lang.Integer applyCount) {
		set("apply_count", applyCount);
		return (M)this;
	}
	
	public java.lang.Integer getApplyCount() {
		return getInt("apply_count");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

}
