package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLabel<M extends BaseLabel<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setLabelName(java.lang.String labelName) {
		set("label_name", labelName);
		return (M)this;
	}
	
	public java.lang.String getLabelName() {
		return getStr("label_name");
	}

	public M setLabelCode(java.lang.String labelCode) {
		set("label_code", labelCode);
		return (M)this;
	}
	
	public java.lang.String getLabelCode() {
		return getStr("label_code");
	}

	public M setLabelPath(java.lang.String labelPath) {
		set("label_path", labelPath);
		return (M)this;
	}
	
	public java.lang.String getLabelPath() {
		return getStr("label_path");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
