package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {

	public M setRegionId(java.lang.Long regionId) {
		set("region_id", regionId);
		return (M)this;
	}
	
	public java.lang.Long getRegionId() {
		return getLong("region_id");
	}

	public M setRegionName(java.lang.String regionName) {
		set("region_name", regionName);
		return (M)this;
	}
	
	public java.lang.String getRegionName() {
		return getStr("region_name");
	}

	public M setRegionCode(java.lang.String regionCode) {
		set("region_code", regionCode);
		return (M)this;
	}
	
	public java.lang.String getRegionCode() {
		return getStr("region_code");
	}

	public M setLevelId(java.lang.Integer levelId) {
		set("level_id", levelId);
		return (M)this;
	}
	
	public java.lang.Integer getLevelId() {
		return getInt("level_id");
	}

	public M setFatherId(java.lang.Integer fatherId) {
		set("father_id", fatherId);
		return (M)this;
	}
	
	public java.lang.Integer getFatherId() {
		return getInt("father_id");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setDr(java.lang.Integer dr) {
		set("dr", dr);
		return (M)this;
	}
	
	public java.lang.Integer getDr() {
		return getInt("dr");
	}

}
