package com.demo.common.model.log;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.log.base.BaseFtpTask;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FtpTask extends BaseFtpTask<FtpTask> {
	public static final FtpTask dao = new FtpTask().dao();
	
	public Page<FtpTask> getAllFtpTask(int current, int pageSize,
			Map<String, String> map) {
		List<Object> paramList = new ArrayList<Object>();
		StringBuilder condition = new StringBuilder();
		String name = map.get("task_name");

		String from = "FROM  ftp_task a where 1=1 ";
		condition.append(from);

		if (!StringUtils.isBlank(name)) {
			condition.append(" and a.task_name like ?");
			paramList.add("%" + name + "%");
		}

		Page<FtpTask> page = paginate(current, pageSize, "SELECT * ",
				condition.toString(), paramList.toArray(new Object[] {}));

		if (page != null && page.getList() != null) {
			if (current > 1 && page.getList().isEmpty()) {
				page = getAllFtpTask(current - 1, pageSize, map);
			}
		}
		return page;
	}

	public List<FtpTask> getLogSourceInfoList() {
		return find("select * from ftp_task");
	}
}
