package com.demo.common.model.log;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.log.base.BaseLogCollectMachine;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogCollectMachine extends BaseLogCollectMachine<LogCollectMachine> {
	public static final LogCollectMachine dao = new LogCollectMachine();
	 public Page<LogCollectMachine> getAllLogCollectMachine(int current, int pageSize, Map<String, String> map) {
		    List<Object> paramList = new ArrayList<Object>();
		    StringBuilder condition = new StringBuilder();
		    String name = map.get("machine_name");

		    String from = "FROM  log_collect_machine a where 1=1 ";
		    condition.append(from);

		    if (!StringUtils.isBlank(name)) {
		      condition.append(" and a.machine_name like ?");
		      paramList.add("%" + name + "%");
		    }

		    Page<LogCollectMachine> page =
		        paginate(current, pageSize, "SELECT * ", condition.toString(),
		            paramList.toArray(new Object[] {}));

		    if (page != null && page.getList() != null) {
		      if (current > 1 && page.getList().isEmpty()) {
		        page = getAllLogCollectMachine(current - 1, pageSize, map);
		      }
		    }
		    return page;
		  }
	 
	 public List<LogCollectMachine> getLogSourceInfoList() {
		 return find("select * from log_collect_machine");
	 }
}
