package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseLogSourceField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogSourceField extends BaseLogSourceField<LogSourceField> {
	public static final LogSourceField dao = new LogSourceField() ;
}
