package com.demo.common.model.log;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.log.base.BaseLogSourceInfo;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogSourceInfo extends BaseLogSourceInfo<LogSourceInfo> {
	public static final LogSourceInfo dao = new LogSourceInfo();
	
	 public Page<LogSourceInfo> getAllLogSourceInfo(int current, int pageSize, Map<String, String> map) {
		    List<Object> paramList = new ArrayList<Object>();
		    StringBuilder condition = new StringBuilder();
		    String name = map.get("src_name");

		    String from = "FROM  log_source_info a,sys_dict b where b.data_type='LogType' and a.src_type=b.data_value ";
		    condition.append(from);

		    if (!StringUtils.isBlank(name)) {
		      condition.append(" and a.src_name like ?");
		      paramList.add("%" + name + "%");
		    }

		    Page<LogSourceInfo> page =
		        paginate(current, pageSize, "SELECT a.*,b.data_name as src_type_str ", condition.toString(),
		            paramList.toArray(new Object[] {}));

		    if (page != null && page.getList() != null) {
		      if (current > 1 && page.getList().isEmpty()) {
		        page = getAllLogSourceInfo(current - 1, pageSize, map);
		      }
		    }
		    return page;
		  }
	 
	 public List<LogSourceInfo> getLogSourceInfoList() {
		 return find("select * from log_source_info");
	 }
}
