package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzLocks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzLocks extends BaseQrtzLocks<QrtzLocks> {
	public static final QrtzLocks dao = new QrtzLocks().dao();
}
