package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzSimpleTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSimpleTriggers extends BaseQrtzSimpleTriggers<QrtzSimpleTriggers> {
	public static final QrtzSimpleTriggers dao = new QrtzSimpleTriggers().dao();
}
