package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzJobDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzJobDetails extends BaseQrtzJobDetails<QrtzJobDetails> {
	public static final QrtzJobDetails dao = new QrtzJobDetails().dao();
}
