package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzFiredTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzFiredTriggers extends BaseQrtzFiredTriggers<QrtzFiredTriggers> {
	public static final QrtzFiredTriggers dao = new QrtzFiredTriggers().dao();
}
