package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzBlobTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzBlobTriggers extends BaseQrtzBlobTriggers<QrtzBlobTriggers> {
	public static final QrtzBlobTriggers dao = new QrtzBlobTriggers().dao();
}
