package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzTriggers extends BaseQrtzTriggers<QrtzTriggers> {
	public static final QrtzTriggers dao = new QrtzTriggers().dao();
}
