package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzPausedTriggerGrps;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzPausedTriggerGrps extends BaseQrtzPausedTriggerGrps<QrtzPausedTriggerGrps> {
	public static final QrtzPausedTriggerGrps dao = new QrtzPausedTriggerGrps().dao();
}
