package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzCalendars;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzCalendars extends BaseQrtzCalendars<QrtzCalendars> {
	public static final QrtzCalendars dao = new QrtzCalendars().dao();
}
