package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzSimpropTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSimpropTriggers extends BaseQrtzSimpropTriggers<QrtzSimpropTriggers> {
	public static final QrtzSimpropTriggers dao = new QrtzSimpropTriggers().dao();
}
