package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzSchedulerState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSchedulerState extends BaseQrtzSchedulerState<QrtzSchedulerState> {
	public static final QrtzSchedulerState dao = new QrtzSchedulerState().dao();
}
