package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseQrtzCronTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzCronTriggers extends BaseQrtzCronTriggers<QrtzCronTriggers> {
	public static final QrtzCronTriggers dao = new QrtzCronTriggers().dao();
}
