package com.demo.common.model.log;

import com.demo.common.model.log.base.BaseSysDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	public static final SysDict dao = new SysDict().dao();
}
