package com.demo.common.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.base.BaseLabel;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Label extends BaseLabel<Label> {
	public static final Label dao = new Label().dao();
	
	 public Page<Label> getAllLabel(int current, int pageSize, Map<String, String> map) {
	    List<Object> paramList = new ArrayList<Object>();
	    StringBuilder condition = new StringBuilder();
	    String name = map.get("Label_name");

	    String from = "FROM  label a where 1=1 ";
	    condition.append(from);

	    if (!StringUtils.isBlank(name)) {
	      condition.append(" and a.Label_name like ?");
	      paramList.add("%" + name + "%");
	    }

	    Page<Label> page =
	        paginate(current, pageSize, "SELECT * ", condition.toString(),
	            paramList.toArray(new Object[] {}));

	    if (page != null && page.getList() != null) {
	      if (current > 1 && page.getList().isEmpty()) {
	        page = getAllLabel(current - 1, pageSize, map);
	      }
	    }
	    return page;
	  }
	 
	 public List<Label> getAllLabel() {
	      String sqlPara = "SELECT * FROM label";
	      return find(sqlPara);
	    }
}
