package com.demo.common.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.base.BasePreOrder;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PreOrder extends BasePreOrder<PreOrder> {
	public static final PreOrder dao = new PreOrder().dao();
	
	 public Page<PreOrder> getAllPreOrder(int current, int pageSize, Map<String, String> map) {
       List<Object> paramList = new ArrayList<Object>();
       StringBuilder condition = new StringBuilder();
       Object id = map.get("id");

       String from = "from pre_order a inner join region b on a.order_area = b.region_id left join product c on a.order_product = c.id  where 1=1 ";
       condition.append(from);

       if (id != null) {
         condition.append(" and a.id like ?");
         paramList.add("%" + id + "%");
       }

       Page<PreOrder> page = paginate(current, pageSize, "SELECT a.*,b.region_name,c.product_name  ", condition.toString(), paramList.toArray(new Object[] {}));

       if (page != null && page.getList() != null) {
         if (current > 1 && page.getList().isEmpty()) {
           page = getAllPreOrder(current - 1, pageSize, map);
         }
       }
       return page;
     }
	 
	 public List<PreOrder> getPreOrders() {
		 String sql = "SELECT a.id,a.order_tel,a.user_name,a.order_time,b.region_name,c.product_name  from pre_order a inner join region b on a.order_area = b.region_id left join product c on a.order_product = c.id order by a.id";
		 return find(sql);
	 }
}
