package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseProductRuleRelation;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductRuleRelation extends BaseProductRuleRelation<ProductRuleRelation> {
	public static final ProductRuleRelation dao = new ProductRuleRelation().dao();
	
	public List<ProductRuleRelation> getProductRuleByProductId(Object productId) {
		 return find("select * from product_rule_relation where product_id=?",new Object[]{productId});
	}
	
	public void deleteByProductId(Long productId) {
		  Db.update("delete from product_rule_relation where product_id=?",new Object[]{productId});
	}
}
