package com.demo.common.model;

import com.demo.common.model.base.BaseProductLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductLabel extends BaseProductLabel<ProductLabel> {
	public static final ProductLabel dao = new ProductLabel().dao();
}
