package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseProductLabel;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductLabel extends BaseProductLabel<ProductLabel> {
	public static final ProductLabel dao = new ProductLabel().dao();
	
	public void deleteByProductId(Long productId) {
		  Db.update("delete from product_label where product_id=?",new Object[]{productId});
	}
	
	public List<ProductLabel> getProductLabelByProductId(Object productId) {
		  return find("select * from product_label where product_id=?",new Object[]{productId});
	}
}
