package com.demo.common.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.demo.common.model.base.BaseSysDict;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	public static final SysDict dao = new SysDict().dao();
	
	 public Page<SysDict> getAllSysDict(int current, int pageSize, Map<String, String> map) {
	    List<Object> paramList = new ArrayList<Object>();
	    StringBuilder condition = new StringBuilder();
	    String type = map.get("data_type");
	    String name = map.get("data_name");

	    String from = "FROM  sys_dict a where 1=1 ";
	    condition.append(from);

	    if (!StringUtils.isBlank(type)) {
	      condition.append(" and a.data_type like ?");
	      paramList.add("%" + type + "%");
	    }
	    if (!StringUtils.isBlank(name)) {
          condition.append(" and a.data_name like ?");
          paramList.add("%" + name + "%");
        }

	    Page<SysDict> page =
	        paginate(current, pageSize, "SELECT * ", condition.toString(),
	            paramList.toArray(new Object[] {}));

	    if (page != null && page.getList() != null) {
	      if (current > 1 && page.getList().isEmpty()) {
	        page = getAllSysDict(current - 1, pageSize, map);
	      }
	    }
	    return page;
	  }
	public List<SysDict> getAllData(Object dataType) {
      String sqlPara = "SELECT * FROM sys_dict WHERE status=1 and data_type=?";
      return find(sqlPara,new Object[]{dataType});
    }
}
