package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzLocks<M extends BaseQrtzLocks<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setLockName(java.lang.String lockName) {
		set("LOCK_NAME", lockName);
		return (M)this;
	}
	
	public java.lang.String getLockName() {
		return getStr("LOCK_NAME");
	}

}
