package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzFiredTriggers<M extends BaseQrtzFiredTriggers<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setEntryId(java.lang.String entryId) {
		set("ENTRY_ID", entryId);
		return (M)this;
	}
	
	public java.lang.String getEntryId() {
		return getStr("ENTRY_ID");
	}

	public M setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
		return (M)this;
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public M setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
		return (M)this;
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public M setInstanceName(java.lang.String instanceName) {
		set("INSTANCE_NAME", instanceName);
		return (M)this;
	}
	
	public java.lang.String getInstanceName() {
		return getStr("INSTANCE_NAME");
	}

	public M setFiredTime(java.lang.Long firedTime) {
		set("FIRED_TIME", firedTime);
		return (M)this;
	}
	
	public java.lang.Long getFiredTime() {
		return getLong("FIRED_TIME");
	}

	public M setPRIORITY(java.lang.Integer PRIORITY) {
		set("PRIORITY", PRIORITY);
		return (M)this;
	}
	
	public java.lang.Integer getPRIORITY() {
		return getInt("PRIORITY");
	}

	public M setSTATE(java.lang.String STATE) {
		set("STATE", STATE);
		return (M)this;
	}
	
	public java.lang.String getSTATE() {
		return getStr("STATE");
	}

	public M setJobName(java.lang.String jobName) {
		set("JOB_NAME", jobName);
		return (M)this;
	}
	
	public java.lang.String getJobName() {
		return getStr("JOB_NAME");
	}

	public M setJobGroup(java.lang.String jobGroup) {
		set("JOB_GROUP", jobGroup);
		return (M)this;
	}
	
	public java.lang.String getJobGroup() {
		return getStr("JOB_GROUP");
	}

	public M setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("IS_NONCONCURRENT", isNonconcurrent);
		return (M)this;
	}
	
	public java.lang.String getIsNonconcurrent() {
		return getStr("IS_NONCONCURRENT");
	}

	public M setRequestsRecovery(java.lang.String requestsRecovery) {
		set("REQUESTS_RECOVERY", requestsRecovery);
		return (M)this;
	}
	
	public java.lang.String getRequestsRecovery() {
		return getStr("REQUESTS_RECOVERY");
	}

}
