package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzSimpropTriggers<M extends BaseQrtzSimpropTriggers<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
		return (M)this;
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public M setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
		return (M)this;
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public M setStrProp1(java.lang.String strProp1) {
		set("STR_PROP_1", strProp1);
		return (M)this;
	}
	
	public java.lang.String getStrProp1() {
		return getStr("STR_PROP_1");
	}

	public M setStrProp2(java.lang.String strProp2) {
		set("STR_PROP_2", strProp2);
		return (M)this;
	}
	
	public java.lang.String getStrProp2() {
		return getStr("STR_PROP_2");
	}

	public M setStrProp3(java.lang.String strProp3) {
		set("STR_PROP_3", strProp3);
		return (M)this;
	}
	
	public java.lang.String getStrProp3() {
		return getStr("STR_PROP_3");
	}

	public M setIntProp1(java.lang.Integer intProp1) {
		set("INT_PROP_1", intProp1);
		return (M)this;
	}
	
	public java.lang.Integer getIntProp1() {
		return getInt("INT_PROP_1");
	}

	public M setIntProp2(java.lang.Integer intProp2) {
		set("INT_PROP_2", intProp2);
		return (M)this;
	}
	
	public java.lang.Integer getIntProp2() {
		return getInt("INT_PROP_2");
	}

	public M setLongProp1(java.lang.Long longProp1) {
		set("LONG_PROP_1", longProp1);
		return (M)this;
	}
	
	public java.lang.Long getLongProp1() {
		return getLong("LONG_PROP_1");
	}

	public M setLongProp2(java.lang.Long longProp2) {
		set("LONG_PROP_2", longProp2);
		return (M)this;
	}
	
	public java.lang.Long getLongProp2() {
		return getLong("LONG_PROP_2");
	}

	public M setDecProp1(java.math.BigDecimal decProp1) {
		set("DEC_PROP_1", decProp1);
		return (M)this;
	}
	
	public java.math.BigDecimal getDecProp1() {
		return get("DEC_PROP_1");
	}

	public M setDecProp2(java.math.BigDecimal decProp2) {
		set("DEC_PROP_2", decProp2);
		return (M)this;
	}
	
	public java.math.BigDecimal getDecProp2() {
		return get("DEC_PROP_2");
	}

	public M setBoolProp1(java.lang.String boolProp1) {
		set("BOOL_PROP_1", boolProp1);
		return (M)this;
	}
	
	public java.lang.String getBoolProp1() {
		return getStr("BOOL_PROP_1");
	}

	public M setBoolProp2(java.lang.String boolProp2) {
		set("BOOL_PROP_2", boolProp2);
		return (M)this;
	}
	
	public java.lang.String getBoolProp2() {
		return getStr("BOOL_PROP_2");
	}

}
