package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogCollectMachine<M extends BaseLogCollectMachine<M>> extends Model<M> implements IBean {

	public M setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
		return (M)this;
	}
	
	public java.lang.String getMachineId() {
		return getStr("machine_id");
	}

	public M setMachineName(java.lang.String machineName) {
		set("machine_name", machineName);
		return (M)this;
	}
	
	public java.lang.String getMachineName() {
		return getStr("machine_name");
	}

	public M setMachineCode(java.lang.String machineCode) {
		set("machine_code", machineCode);
		return (M)this;
	}
	
	public java.lang.String getMachineCode() {
		return getStr("machine_code");
	}

	public M setMachineIp(java.lang.String machineIp) {
		set("machine_ip", machineIp);
		return (M)this;
	}
	
	public java.lang.String getMachineIp() {
		return getStr("machine_ip");
	}

	public M setServicePath(java.lang.String servicePath) {
		set("service_path", servicePath);
		return (M)this;
	}
	
	public java.lang.String getServicePath() {
		return getStr("service_path");
	}

	public M setServiceStatus(java.lang.String serviceStatus) {
		set("service_status", serviceStatus);
		return (M)this;
	}
	
	public java.lang.String getServiceStatus() {
		return getStr("service_status");
	}

}
