package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFtpTask<M extends BaseFtpTask<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setFtpHost(java.lang.String ftpHost) {
		set("ftp_host", ftpHost);
		return (M)this;
	}
	
	public java.lang.String getFtpHost() {
		return getStr("ftp_host");
	}

	public M setFtpPort(java.lang.String ftpPort) {
		set("ftp_port", ftpPort);
		return (M)this;
	}
	
	public java.lang.String getFtpPort() {
		return getStr("ftp_port");
	}

	public M setFtpUser(java.lang.String ftpUser) {
		set("ftp_user", ftpUser);
		return (M)this;
	}
	
	public java.lang.String getFtpUser() {
		return getStr("ftp_user");
	}

	public M setFtpPwd(java.lang.String ftpPwd) {
		set("ftp_pwd", ftpPwd);
		return (M)this;
	}
	
	public java.lang.String getFtpPwd() {
		return getStr("ftp_pwd");
	}

	public M setFtpPath(java.lang.String ftpPath) {
		set("ftp_path", ftpPath);
		return (M)this;
	}
	
	public java.lang.String getFtpPath() {
		return getStr("ftp_path");
	}

	public M setQutzId(java.lang.String qutzId) {
		set("qutz_id", qutzId);
		return (M)this;
	}
	
	public java.lang.String getQutzId() {
		return getStr("qutz_id");
	}

	public M setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
		return (M)this;
	}
	
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}

}
