package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzCalendars<M extends BaseQrtzCalendars<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setCalendarName(java.lang.String calendarName) {
		set("CALENDAR_NAME", calendarName);
		return (M)this;
	}
	
	public java.lang.String getCalendarName() {
		return getStr("CALENDAR_NAME");
	}

	public M setCALENDAR(byte[] CALENDAR) {
		set("CALENDAR", CALENDAR);
		return (M)this;
	}
	
	public byte[] getCALENDAR() {
		return get("CALENDAR");
	}

}
