package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzJobDetails<M extends BaseQrtzJobDetails<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setJobName(java.lang.String jobName) {
		set("JOB_NAME", jobName);
		return (M)this;
	}
	
	public java.lang.String getJobName() {
		return getStr("JOB_NAME");
	}

	public M setJobGroup(java.lang.String jobGroup) {
		set("JOB_GROUP", jobGroup);
		return (M)this;
	}
	
	public java.lang.String getJobGroup() {
		return getStr("JOB_GROUP");
	}

	public M setDESCRIPTION(java.lang.String DESCRIPTION) {
		set("DESCRIPTION", DESCRIPTION);
		return (M)this;
	}
	
	public java.lang.String getDESCRIPTION() {
		return getStr("DESCRIPTION");
	}

	public M setJobClassName(java.lang.String jobClassName) {
		set("JOB_CLASS_NAME", jobClassName);
		return (M)this;
	}
	
	public java.lang.String getJobClassName() {
		return getStr("JOB_CLASS_NAME");
	}

	public M setIsDurable(java.lang.String isDurable) {
		set("IS_DURABLE", isDurable);
		return (M)this;
	}
	
	public java.lang.String getIsDurable() {
		return getStr("IS_DURABLE");
	}

	public M setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("IS_NONCONCURRENT", isNonconcurrent);
		return (M)this;
	}
	
	public java.lang.String getIsNonconcurrent() {
		return getStr("IS_NONCONCURRENT");
	}

	public M setIsUpdateData(java.lang.String isUpdateData) {
		set("IS_UPDATE_DATA", isUpdateData);
		return (M)this;
	}
	
	public java.lang.String getIsUpdateData() {
		return getStr("IS_UPDATE_DATA");
	}

	public M setRequestsRecovery(java.lang.String requestsRecovery) {
		set("REQUESTS_RECOVERY", requestsRecovery);
		return (M)this;
	}
	
	public java.lang.String getRequestsRecovery() {
		return getStr("REQUESTS_RECOVERY");
	}

	public M setJobData(byte[] jobData) {
		set("JOB_DATA", jobData);
		return (M)this;
	}
	
	public byte[] getJobData() {
		return get("JOB_DATA");
	}

}
