package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogSourceField<M extends BaseLogSourceField<M>> extends Model<M> implements IBean {

	public M setFieldId(java.lang.String fieldId) {
		set("field_id", fieldId);
		return (M)this;
	}
	
	public java.lang.String getFieldId() {
		return getStr("field_id");
	}

	public M setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
		return (M)this;
	}
	
	public java.lang.String getFieldName() {
		return getStr("field_name");
	}

	public M setFieldValue(java.lang.String fieldValue) {
		set("field_value", fieldValue);
		return (M)this;
	}
	
	public java.lang.String getFieldValue() {
		return getStr("field_value");
	}

	public M setFieldDesc(java.lang.String fieldDesc) {
		set("field_desc", fieldDesc);
		return (M)this;
	}
	
	public java.lang.String getFieldDesc() {
		return getStr("field_desc");
	}

	public M setSourceId(java.lang.String sourceId) {
		set("source_id", sourceId);
		return (M)this;
	}
	
	public java.lang.String getSourceId() {
		return getStr("source_id");
	}

}
