package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzSimpleTriggers<M extends BaseQrtzSimpleTriggers<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
		return (M)this;
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public M setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
		return (M)this;
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public M setRepeatCount(java.lang.Long repeatCount) {
		set("REPEAT_COUNT", repeatCount);
		return (M)this;
	}
	
	public java.lang.Long getRepeatCount() {
		return getLong("REPEAT_COUNT");
	}

	public M setRepeatInterval(java.lang.Long repeatInterval) {
		set("REPEAT_INTERVAL", repeatInterval);
		return (M)this;
	}
	
	public java.lang.Long getRepeatInterval() {
		return getLong("REPEAT_INTERVAL");
	}

	public M setTimesTriggered(java.lang.Long timesTriggered) {
		set("TIMES_TRIGGERED", timesTriggered);
		return (M)this;
	}
	
	public java.lang.Long getTimesTriggered() {
		return getLong("TIMES_TRIGGERED");
	}

}
