package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQrtzSchedulerState<M extends BaseQrtzSchedulerState<M>> extends Model<M> implements IBean {

	public M setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
		return (M)this;
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public M setInstanceName(java.lang.String instanceName) {
		set("INSTANCE_NAME", instanceName);
		return (M)this;
	}
	
	public java.lang.String getInstanceName() {
		return getStr("INSTANCE_NAME");
	}

	public M setLastCheckinTime(java.lang.Long lastCheckinTime) {
		set("LAST_CHECKIN_TIME", lastCheckinTime);
		return (M)this;
	}
	
	public java.lang.Long getLastCheckinTime() {
		return getLong("LAST_CHECKIN_TIME");
	}

	public M setCheckinInterval(java.lang.Long checkinInterval) {
		set("CHECKIN_INTERVAL", checkinInterval);
		return (M)this;
	}
	
	public java.lang.Long getCheckinInterval() {
		return getLong("CHECKIN_INTERVAL");
	}

}
