package com.demo.common.model.log.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSrcCollectMachine<M extends BaseSrcCollectMachine<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCollectId(java.lang.String collectId) {
		set("collect_id", collectId);
		return (M)this;
	}
	
	public java.lang.String getCollectId() {
		return getStr("collect_id");
	}

	public M setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
		return (M)this;
	}
	
	public java.lang.String getMachineId() {
		return getStr("machine_id");
	}

}
